Feature/rec 24
bremade/recify pull request #19
Opened 2020-09-20 19:17 UTC by matthinc

2020-09-30 09:22 UTC, bremade requested changes
For the most parts great job. I realy like the step system :thumbsup:
What is still missing in general tho are input checks. I was able to create a recipe with empty ingredients and empty steps etc. So either we should add default values or check the input and give direct feedback.

2020-09-30 09:22 UTC, bremade commented on frontend/src/components/Time.svelte
> +        <Textfield label="Hours" bind:value={hours} class="fullwidth" type="number" />
Textfields can be negative

2020-09-30 09:22 UTC, bremade commented on frontend/src/pages/recipe/new.svelte
> +                <Tags onlyUnique={true} placeholder="Tags" tags={recipe.tags} autoComplete={allTags} />
For my taste the deep black as background color is a little bit to much. Would change it to our material theme color #2196f3

2020-09-30 09:22 UTC, bremade commented on frontend/src/pages/recipe/new.svelte
> +                    <td><Textfield bind:value={ingredient.amount} class="fullwidth"/></td>
Amount can be negative

2020-09-30 09:22 UTC, bremade commented on frontend/src/pages/recipe/new.svelte
> +            {:else if current_step === 5}
Do we realy need an extra step for that? We could add the finish button to the tags step and then add an extra popup to confirm the creation.

2020-09-30 14:08 UTC, matthinc commented on frontend/src/pages/recipe/new.svelte
> +            {:else if current_step === 5}
I actually like this from an UX point of view.
You can go back to a step, change something and then go publish-step and publish the recipe.
I also plan to add some more stuff in this step (maybe a preview or something like that).

2020-10-01 11:03 UTC, bremade approved these changes
LGTM

2020-10-01 11:04 UTC, merged